### ISSUE TITLE
Wrong 4 bytes at the end

### ISSUE THREAD

**Issue by Altai-man** [tony-o/perl6-encoding-huffman-pp6#3]
I'm currently working on hpack http2 encoder/decoder and it seems we have one more bug.

When you do standalone "encode-decode" process, it works perfectly, except for comparing to other Huffman encoding suites. As example, try to code word `customkey` - it gives you result:
`Buf[uint8]:0x<25 a8 49 e9 ea 5f 5f ff ff ff 80>`
 While in, for example, [hyper](https://github.com/python-hyper/hpack/) project encoder will encode it like this:
`Buf[uint8]:0x<25 a8 49 e9 ea 5f 5f 89 41 6a 41>`
 I tried other words from tests of hyper implementation and got some results, for example, if you try to encode `/jimiscool/`, you will get this:
`Buf[uint8]:0x<63 a1 a9 32 08 73 d0 c7 ff ff ff e0>`
 It's right at start, but last four digits are wrong. This pattern `ff ff ff`, I suppose, will repeat for other words too.

I will try to dig in it soon and I hope I will be able to send a pull request, but any help or advice will be appreciated.

**Comment by tony-o** [comment]
@Altai-man - I looked more into this last week and it looks like my module is actually wrong for adding the `_eos` bits and that the bytes following (the ones that are off from what is expected) are actually implemented from HPACK and not the huffman encoding code.  So, there is a bug in this code but it isn't that the last bits are wrong, it's that it's adding the `_eos` bits indiscriminately.  Thoughts?

**Comment by Altai-man** [comment]
I've found an hpack implementation in nginx sources, written in perl5 and will try to look at their approach to `_eos` and friends. Will see if it helps me to understand encoding process better to improve my code and usage of Huffman. Thanks for your efforts.

**Comment by Altai-man** [comment]
@tony-o, okay, I've investigated the encoding process. You certainly are right about the reason: it's hpack adds encoded length and `_eos` to the buffer.
We should probably add a flag which shows if function must to add `_eos` or not to the arguments(to be flexible enough if anyone else will to reimplement hpack), I think. I see it like this:

``` perl6
sub huffman-encode(Buf[uint8] $s, %codes = %huffman-http2, Bool :$eos = True) is export {
# And then...
my @range;
if $eos {
    @range = ($bits.comb, %codes<_eos>.comb).flat;
} else {
    @range = $bits.comb;
}
for $range -> $c # And so goes on.
```

And then encoded buffer(with(for daily encoding) or without(for actual hpack implementations) `_eos`) will be extended with length and _eos bits in an hpack part. Is it appropriate?
If so, I'll write a properly PR and send it.

**Comment by Altai-man** [comment]
Can be closed, since we have https://github.com/perl6/ecosystem/commit/f5f46bbace now.
